theme: minima
title: Understanding GitHub Pages & GitHub Flow
author: Prakirth
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  
  GitHub Flow & GitHub Pages are some basic and awesome tools to start
  with before proceeding to work on projects with a Team.
  Personal Opinion - working on these tools in an editor (Virtual Studio Code) or
  Terminal (CLI) would be a better learning experience.
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  prak112 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
